-- 코드를 입력하세요
WITH COUNT_BOOK AS(
    SELECT BOOK_ID, SUM(SALES) AS SUM_S
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
)

SELECT B.AUTHOR_ID, ATH.AUTHOR_NAME, B.CATEGORY, SUM(CB.SUM_S * B.PRICE) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS ATH ON B.AUTHOR_ID=ATH.AUTHOR_ID
JOIN COUNT_BOOK AS CB ON B.BOOK_ID = CB.BOOK_ID
GROUP BY B.AUTHOR_ID, ATH.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC
