-- 코드를 작성해주세요
WITH FIR_GEN AS (
    SELECT *
    FROM ECOLI_DATA AS FIR_E
    WHERE FIR_E.PARENT_ID IS NULL
), SECON_GEN AS(
    SELECT *
    FROM ECOLI_DATA AS THD_E
    WHERE THD_E.PARENT_ID IN (SELECT ID FROM FIR_GEN)
)

SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (SELECT ID FROM SECON_GEN)
ORDER BY ID ASC


