-- 코드를 입력하세요
WITH MAR_ONLINE_SALE AS(
    SELECT *
    FROM ONLINE_SALE
    WHERE MONTH(SALES_DATE) = 3 AND YEAR(SALES_DATE)=2022
), MAR_OFFLINE_SALE AS(
    SELECT *
    FROM OFFLINE_SALE
    WHERE MONTH(SALES_DATE) = 3 AND YEAR(SALES_DATE)=2022
)

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
       PRODUCT_ID,
       USER_ID,
       SALES_AMOUNT
FROM MAR_ONLINE_SALE
UNION ALL
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
       PRODUCT_ID,
       NULL,
       SALES_AMOUNT
FROM MAR_OFFLINE_SALE
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;