-- 코드를 입력하세요
WITH POSS_CAR AS(
SELECT CH.HISTORY_ID, CH.CAR_ID, CC.CAR_TYPE, CC.DAILY_FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
JOIN CAR_RENTAL_COMPANY_CAR AS CC ON CH.CAR_ID = CC.CAR_ID
WHERE (CC.CAR_TYPE = '세단' OR CC.CAR_TYPE = 'SUV') AND NOT EXISTS (
      SELECT 1 
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH 
      WHERE CH.CAR_ID = CC.CAR_ID 
        AND CH.START_DATE <= '2022-11-30'
        AND CH.END_DATE >= '2022-11-01'
  ))

SELECT DISTINCT PC.CAR_ID, PC.CAR_TYPE, FLOOR(PC.DAILY_FEE * 30 * (1-0.01*CP.DISCOUNT_RATE)) AS FEE
FROM POSS_CAR AS PC
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP ON PC.CAR_TYPE = CP.CAR_TYPE AND CP.DURATION_TYPE = '30일 이상'
WHERE PC.DAILY_FEE * 30 * (1-0.01*CP.DISCOUNT_RATE) >= 500000 AND PC.DAILY_FEE * 30 * (1-0.01*CP.DISCOUNT_RATE)<2000000
ORDER BY FEE DESC, PC.CAR_TYPE ASC, PC.CAR_ID DESC