-- 코드를 입력하세요
WITH TYPE_FAVORITE AS(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_F
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM TYPE_FAVORITE AS TF
JOIN REST_INFO AS RI ON TF.FOOD_TYPE = RI.FOOD_TYPE AND TF.MAX_F = RI.FAVORITES
ORDER BY RI.FOOD_TYPE DESC