WITH SEOUL_PLACE AS (
    SELECT *
      FROM REST_INFO
     WHERE ADDRESS LIKE '서울%'
)
SELECT SP.REST_ID,
       SP.REST_NAME,
       SP.FOOD_TYPE,
       SP.FAVORITES,
       SP.ADDRESS,
       -- 화면에는 반올림된 값만 보여주고
       ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE 
  FROM SEOUL_PLACE SP
  JOIN REST_REVIEW RR 
    ON SP.REST_ID = RR.REST_ID
 GROUP BY SP.REST_ID, SP.REST_NAME, SP.FOOD_TYPE, SP.FAVORITES, SP.ADDRESS
 -- 정렬은 실제 평균값(AVG)으로 내림차순 -> 그 다음 즐겨찾기수 내림차순
 ORDER BY AVG(RR.REVIEW_SCORE) DESC,
          SP.FAVORITES DESC;