-- 코드를 입력하세요
SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS TLNO,
CASE
WHEN FREEZER_YN = 'Y' THEN 'Y'
ELSE 'N'
END AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE LOCATE('경기도', ADDRESS)
ORDER BY WAREHOUSE_ID ASC
