-- 코드를 입력하세요
WITH JOIN_2021 AS (
    SELECT *
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
), AL_COUNT AS (
    SELECT COUNT(*) AS AC
    FROM JOIN_2021
)

SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT AC FROM AL_COUNT), 1) AS PUCHASE_RATIO
FROM ONLINE_SALE AS OS
INNER JOIN JOIN_2021 AS J ON J.USER_ID=OS.USER_ID
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC