WITH DATE_DIFF AS (
SELECT H.HISTORY_ID, DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENT_DATE, C.DAILY_FEE AS DAILY_FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
JOIN CAR_RENTAL_COMPANY_CAR AS C ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '트럭' )

SELECT HISTORY_ID, FLOOR(((100-
(CASE
WHEN RENT_DATE>=90 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')
    WHEN RENT_DATE >= 30 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')
    WHEN RENT_DATE >= 7 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')
    ELSE 0
    END
))*0.01*DAILY_FEE*RENT_DATE)) AS FEE
FROM DATE_DIFF
ORDER BY FEE DESC, HISTORY_ID DESC
