-- 코드를 입력하세요
SELECT AP.APNT_NO AS APNT_NO, PT.PT_NAME,PT.PT_NO , AP.MCDP_CD, DR.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AS AP
JOIN PATIENT AS PT ON AP.PT_NO = PT.PT_NO
JOIN DOCTOR AS DR ON AP.MDDR_ID = DR.DR_ID
WHERE AP.MCDP_CD = 'CS' AND AP.APNT_YMD >= DATE('2022-04-13') AND AP.APNT_YMD < DATE('2022-04-14') AND AP.APNT_CNCL_YN = 'N'
ORDER BY AP.APNT_YMD ASC