-- 코드를 작성해주세요
WITH AVG_SCORE AS(
    SELECT EMP_NO, AVG(SCORE) AS A_S
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT E.EMP_NO, E.EMP_NAME,(
    CASE
    WHEN A.A_S >= 96 THEN 'S'
    WHEN A.A_S >= 90 THEN 'A'
    WHEN A.A_S >= 80 THEN 'B'
    ELSE 'C'
    END
) AS GRADE, 
(CASE
    WHEN A.A_S >= 96 THEN FLOOR(E.SAL * 0.2)
    WHEN A.A_S >= 90 THEN FLOOR(E.SAL * 0.15)
    WHEN A.A_S >= 80 THEN FLOOR(E.SAL * 0.1)
    ELSE 0
    END
) AS BONUS
FROM HR_EMPLOYEES AS E
JOIN AVG_SCORE AS A ON E.EMP_NO = A.EMP_NO
ORDER BY EMP_NO ASC