-- 코드를 입력하세요
WITH MAX_REVIEWER AS(
    SELECT MEMBER_ID, COUNT(MEMBER_ID) AS COUNT_MEMBER
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT_MEMBER DESC
    LIMIT 1
)

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS RR
JOIN MEMBER_PROFILE AS MP ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID = (SELECT MEMBER_ID FROM MAX_REVIEWER)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC