-- 코드를 작성해주세요
SELECT A.ID, A.GENOTYPE, ORG.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS ORG
RIGHT JOIN ECOLI_DATA AS A ON ORG.ID = A.PARENT_ID
WHERE (ORG.GENOTYPE & A.GENOTYPE) = ORG.GENOTYPE
ORDER BY ID ASC
