-- 코드를 작성해주세요
SELECT DISTINCT DEV.ID, DEV.EMAIL, DEV.FIRST_NAME, DEV.LAST_NAME
FROM DEVELOPERS AS DEV
INNER JOIN SKILLCODES AS SKI ON DEV.SKILL_CODE & SKI.CODE
WHERE DEV.SKILL_CODE & (
SELECT CODE
FROM SKILLCODES
WHERE NAME='Python'
)
or DEV.SKILL_CODE & (
SELECT CODE
FROM SKILLCODES
WHERE NAME='C#'
)
ORDER BY DEV.ID