-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
(SELECT MAX(SIZE_OF_COLONY)
                  FROM ECOLI_DATA AS B
                  WHERE DATE_FORMAT(B.DIFFERENTIATION_DATE, '%Y') = DATE_FORMAT(A.DIFFERENTIATION_DATE, '%Y')
) - SIZE_OF_COLONY
AS YEAR_DEV,
ID
FROM ECOLI_DATA AS A
ORDER BY YEAR ASC, YEAR_DEV ASC

