-- 코드를 작성해주세요
WITH BIG_FISH AS(
SELECT FI.FISH_TYPE AS FISH_TYPE, FNI.FISH_NAME AS FISH_NAME, MAX(FI.LENGTH) AS LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI ON FNI.FISH_TYPE = FI.FISH_TYPE
GROUP BY FI.FISH_TYPE, FNI.FISH_NAME
)

SELECT FN.ID, BF.FISH_NAME, BF.LENGTH
FROM BIG_FISH AS BF
JOIN FISH_INFO AS FN ON BF.FISH_TYPE= FN.FISH_TYPE AND BF.LENGTH = FN.LENGTH
