-- 코드를 입력하세요
SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY AS UGR
JOIN USED_GOODS_BOARD AS UGB ON UGR.BOARD_ID = UGB.BOARD_ID
WHERE MONTH(UGB.CREATED_DATE) = 10 and YEAR(UGB.CREATED_DATE) = 2022
ORDER BY UGR.CREATED_DATE, UGB.TITLE