-- 코드를 입력하세요
WITH BOOK_SALES_GROUP AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES AS BS
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
)

SELECT B.CATEGORY, SUM(G.SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN BOOK_SALES_GROUP AS G ON B.BOOK_ID=G.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY