-- 코드를 입력하세요
WITH MAX_PRICE_FP AS(
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('식용유', '국', '김치', '과자')
GROUP BY CATEGORY
)

SELECT FP.CATEGORY, MP.MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
JOIN MAX_PRICE_FP AS MP ON FP.CATEGORY = MP.CATEGORY AND FP.PRICE = MP.MAX_PRICE
ORDER BY MP.MAX_PRICE DESC;