-- 코드를 작성해주세요
WITH FISH_AVG AS(
    SELECT FISH_TYPE, AVG(
    CASE
        WHEN LENGTH <= 10 OR LENGTH IS NULL THEN 10
        ELSE LENGTH
        END
    ) AS FAV
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT COUNT(*) AS FISH_COUNT, MAX(FI.LENGTH) AS MAX_LENGTH, FI.FISH_TYPE
FROM FISH_INFO AS FI
JOIN FISH_AVG AS FA ON FI.FISH_TYPE = FA.FISH_TYPE
WHERE FA.FAV >= 33
GROUP BY FI.FISH_TYPE
ORDER BY FI.FISH_TYPE ASC
